/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.gui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import my.info.Student_Info;
public class AddUI extends javax.swing.JFrame {

    /**
     * Creates new form AddUI
     */
    public AddUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	Student_Info temp_acct = new Student_Info();
        genderButtonGroup = new javax.swing.ButtonGroup();
        labelID = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelBDate = new javax.swing.JLabel();
        labelCollege = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        textMidName = new javax.swing.JTextField();
        labelMenu = new javax.swing.JLabel();
        labelLast = new javax.swing.JLabel();
        labelMid = new javax.swing.JLabel();
        lableFirst = new javax.swing.JLabel();
        maleGButton = new javax.swing.JRadioButton();
        femaleGButton = new javax.swing.JRadioButton();
        textBlockNum = new javax.swing.JTextField();
        textStreet = new javax.swing.JTextField();
        textBrgy = new javax.swing.JTextField();
        textCity = new javax.swing.JTextField();
        labelBlockNum = new javax.swing.JLabel();
        labelStreet = new javax.swing.JLabel();
        labelBrgy = new javax.swing.JLabel();
        labelCity = new javax.swing.JLabel();
        comboBoxMonth = new javax.swing.JComboBox<>();
        comboBoxDay = new javax.swing.JComboBox<>();
        comboBoxYear = new javax.swing.JComboBox<>();
        collegePane = new javax.swing.JScrollPane();
        collegeList = new javax.swing.JList<>();
        labelCourse = new javax.swing.JLabel();
        coursePane = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList<>();
        buttonCancel = new javax.swing.JButton();
        buttonProceed = new javax.swing.JButton();
        labelYearLvl = new javax.swing.JLabel();
        comboBoxYearLvl = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Account Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        labelID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelID.setText("ID Number:");

        labelName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelName.setText("Name:");

        labelGender.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelGender.setText("Gender:");

        labelAddress.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelAddress.setText("Address:");

        labelBDate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelBDate.setText("Birthdate:");

        labelCollege.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelCollege.setText("College:");

        textID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textIDFocusLost(evt);
                if(!(textID.getText().isEmpty())){
                	temp_acct.setIdnum(Integer.parseInt(textID.getText()));
                }
                
            }
        });
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
                if(!(textID.getText().isEmpty())){
                	temp_acct.setIdnum(Integer.parseInt(textID.getText()));
                }
            }
        });

        textLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                temp_acct.setL_name(textLastName.getText());
            }
        });
        textLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLastNameActionPerformed(evt);
                temp_acct.setL_name(textLastName.getText());
            }
        });

        textFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFirstNameFocusLost(evt);
                temp_acct.setF_name(textFirstName.getText());
            }
        });
        textFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFirstNameActionPerformed(evt);
                temp_acct.setF_name(textFirstName.getText());
            }
        });

        textMidName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMidNameFocusLost(evt);
                temp_acct.setM_name(textMidName.getText());
            }
        });
        textMidName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMidNameActionPerformed(evt);
                temp_acct.setM_name(textMidName.getText());
            }
        });

        labelMenu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelMenu.setText("New Account Menu:");

        labelLast.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelLast.setText("Last Name");

        labelMid.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelMid.setText("Middle Name");

        lableFirst.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lableFirst.setText("First Name");

        genderButtonGroup.add(maleGButton);
        maleGButton.setText("Male");
        maleGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleGButtonActionPerformed(evt);
                temp_acct.setGender("M".charAt(0));
            }
        });

        genderButtonGroup.add(femaleGButton);
        femaleGButton.setText("Female");
        femaleGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleGButtonActionPerformed(evt);
                temp_acct.setGender("F".charAt(0));
            }
        });

        textBlockNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textBlockNumFocusLost(evt);
                temp_acct.setAd_house_num(Integer.parseInt(textBlockNum.getText()));
            }
        });
        textBlockNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBlockNumActionPerformed(evt);
                temp_acct.setAd_house_num(Integer.parseInt(textBlockNum.getText()));
            }
        });

        textStreet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textStreetFocusLost(evt);
                temp_acct.setAd_street(textStreet.getText());
            }
        });
        textStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textStreetActionPerformed(evt);
                temp_acct.setAd_street(textStreet.getText());
            }
        });

        textBrgy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textBrgyFocusLost(evt);
                temp_acct.setAd_brgy(textBrgy.getText());
            }
        });
        textBrgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBrgyActionPerformed(evt);
                temp_acct.setAd_brgy(textBrgy.getText());
            }
        });

        textCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textCityFocusLost(evt);
                temp_acct.setAd_city(textCity.getText());
            }
        });
        textCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCityActionPerformed(evt);
                temp_acct.setAd_city(textCity.getText());
            }
        });

        labelBlockNum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelBlockNum.setText("Block #");

        labelStreet.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelStreet.setText("Street");

        labelBrgy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelBrgy.setText("Brgy/Compound");

        labelCity.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        labelCity.setText("City/Municipal");
        
        
        //int month = 1;
        Calendar cal = Calendar.getInstance();
        comboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        comboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMonthActionPerformed(evt);
                try {
					cal.setTime(new SimpleDateFormat("MMM").parse((String) comboBoxMonth.getSelectedItem()));
				} catch (ParseException e) {
					e.printStackTrace();
				}
                
                int month = cal.get(Calendar.MONTH) + 1;

                if(month==1 || month==3 || month==5 || month==7 || month==8 || month==10 || month==12){
                	String[] day = new String[31];
                	for(int i=0; i<31; i++){
                		day[i]=""+(i+1);
                	}
                	comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(day));
                }
                else{
                	String[] day = new String[30];
                	for(int i=0; i<30; i++){
                		day[i]=""+(i+1);
                	}
                	comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(day));
                }
            }
        });

        String[] day = new String[31];
    	for(int i=0; i<31; i++){
    		day[i]=""+(i+1);
    	}
    	comboBoxDay.setModel(new javax.swing.DefaultComboBoxModel<>(day));
        comboBoxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDayActionPerformed(evt);
            }
        });
        String year[] = new String[50];
        for(int i=0; i<50; i++){
        	year[i]=""+(i+1970);
        }
        comboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(year));
        comboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxYearActionPerformed(evt);
            }
        });
        
        

        collegeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CIT", "CNSM", "CHS","CPA", "CBAA", "COE" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            
            
        });
        collegeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        collegeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collegeListMouseClicked(evt);
                courseList.setModel(new javax.swing.AbstractListModel<String>() {
                    String[] strings = returnCourseList(collegeList.getSelectedValue());
                    public int getSize() { return strings.length; }
                    public String getElementAt(int i) { return strings[i]; }
                });
            }
        });
        collegePane.setViewportView(collegeList);

        labelCourse.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelCourse.setText("Course:");


        courseList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        courseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseListMouseClicked(evt);
            }
        });
        coursePane.setViewportView(courseList);

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
                dispose();
            }
        });

        buttonProceed.setText("Proceed");
        buttonProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
                buttonProceedActionPerformed(evt);
                
                if(checkIdNum(temp_acct.getIdnum())){
                	new ExistingIdError().setVisible(true);
                	return;
                	
                }
                Calendar cal_m = null;
                int t_month, t_day;
                try {
					cal.setTime(new SimpleDateFormat("MMM").parse((String) comboBoxMonth.getSelectedItem()));
				} catch (ParseException e) {
					e.printStackTrace();
				}
                
                t_month = cal.get(Calendar.MONTH) + 1;
                t_day = Integer.parseInt(comboBoxDay.getSelectedItem().toString());
                temp_acct.setBdate(comboBoxYear.getSelectedItem()+"-"+String.format("%02d", t_month)+"-"+String.format("%02d", t_day));
                temp_acct.setCollege(collegeList.getSelectedValue());
                temp_acct.setCourse(courseList.getSelectedValue());
                temp_acct.setYear_lvl(comboBoxYearLvl.getSelectedItem().toString());
                dispose();
                new AddConfirmMessage(temp_acct).setVisible(true);
            }
        });
        
        labelYearLvl.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        labelYearLvl.setText("Year");

        comboBoxYearLvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year", "3rd Year", "4th Year", "5th Year", "Irregular Year" }));
        comboBoxYearLvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxYearLvlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelID)
                            .addComponent(labelName)
                            .addComponent(labelGender)
                            .addComponent(labelAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femaleGButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(labelBlockNum)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelStreet)
                                                .addGap(32, 32, 32)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelBrgy)
                                            .addComponent(textBrgy, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCity))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textID, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(labelLast))
                                                    .addComponent(textLastName))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(16, 16, 16)
                                                        .addComponent(lableFirst))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(maleGButton)
                                                .addGap(97, 97, 97)
                                                .addComponent(labelYearLvl)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textMidName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelMid))
                                            .addComponent(comboBoxYearLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonProceed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCancel)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBDate)
                                    .addComponent(labelCollege))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(collegePane))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCourse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coursePane, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMenu)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMidName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLast)
                    .addComponent(lableFirst)
                    .addComponent(labelMid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender)
                    .addComponent(maleGButton)
                    .addComponent(labelYearLvl)
                    .addComponent(comboBoxYearLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(femaleGButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(textBlockNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBrgy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBlockNum)
                    .addComponent(labelStreet)
                    .addComponent(labelBrgy)
                    .addComponent(labelCity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBDate)
                    .addComponent(comboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCollege)
                    .addComponent(collegePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCourse)
                    .addComponent(coursePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonProceed))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void textMidNameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void maleGButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void textBlockNumActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textStreetActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void textBrgyActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void textCityActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void textLastNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void textFirstNameActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void textIDFocusLost(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
    }                                

    private void textLastNameFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void textFirstNameFocusLost(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void textMidNameFocusLost(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void femaleGButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void textBlockNumFocusLost(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void textStreetFocusLost(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void textBrgyFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void textCityFocusLost(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void comboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void comboBoxDayActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void comboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void buttonProceedActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
        
    }                                             

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        
    }                                            

    private void collegeListMouseClicked(java.awt.event.MouseEvent evt) {                                         
        //asdasdasd
    }                                        

    private void courseListMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //adasdasdasdasd
    }
    
    private void comboBoxYearLvlActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    } 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUI().setVisible(true);
            }
        });
    }
    
    public String[] returnCourseList(String college){
    	List <String> courseList = new ArrayList<String>();
    	switch(college){
			case "CNSM":
				courseList.addAll(Arrays.asList("BS-Biology", "BS-Zoology", "BS-Chemistry", "BS-Math", "BS-Physics"));
				break;
			case "CHS":
				courseList.addAll(Arrays.asList("BS-Nursing"));
				break;
			case "CSSH":
				courseList.addAll(Arrays.asList("AB-English", "AB-History", "AB-Philosophy", "AB-Filipino", "BS-Psychology"));
				break;
			case "CPA":
				courseList.addAll(Arrays.asList("BS-PublicAd", "PS-SocialWork"));
				break;
			case "CBAA":
				courseList.addAll(Arrays.asList("BS-Accountacy", "BS-Marketing", "BSA-Management", "BS-Economics"));
				break;
			case "COE":
				courseList.addAll(Arrays.asList("BS-C.Engineering", "BS-M.Engineering", "BS-Ch.Engineering", "BS-A.Engineering","BS-E.Engineering", "BS-EC.Engineering"));
				break;
			case "CIT":
				courseList.addAll(Arrays.asList("BS-IT", "BS-ComputerScience"));
				break;
		}
    	
    	return courseList.toArray(new String[0]);
    }
    public static boolean checkIdNum(int temp_id){
		boolean idnum_checked = false;
		Connection con = null;
    	
		try{
			Class.forName("org.postgresql.Driver");
			con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/student_db", "postgres", "apipahdessopolao");
			PreparedStatement stmt = con.prepareStatement("SELECT idnum FROM student");
			ResultSet rs = stmt.executeQuery();
			
			while(rs.next()){
				if(rs.getInt("idnum") == temp_id){
					idnum_checked = true;
					break;
				}
			}
			
		} catch(Exception ex){
			System.out.println(ex.getMessage());
		}
		
		return idnum_checked;
		
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonProceed;
    private javax.swing.JList<String> collegeList;
    private javax.swing.JScrollPane collegePane;
    private javax.swing.JComboBox<String> comboBoxDay;
    private javax.swing.JComboBox<String> comboBoxMonth;
    private javax.swing.JComboBox<String> comboBoxYear;
    private javax.swing.JComboBox<String> comboBoxYearLvl;
    private javax.swing.JList<String> courseList;
    private javax.swing.JScrollPane coursePane;
    private javax.swing.JRadioButton femaleGButton;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelBDate;
    private javax.swing.JLabel labelBlockNum;
    private javax.swing.JLabel labelBrgy;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelCollege;
    private javax.swing.JLabel labelCourse;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelLast;
    private javax.swing.JLabel labelMenu;
    private javax.swing.JLabel labelMid;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel lableFirst;
    private javax.swing.JLabel labelYearLvl;
    private javax.swing.JRadioButton maleGButton;
    private javax.swing.JTextField textBlockNum;
    private javax.swing.JTextField textBrgy;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textMidName;
    private javax.swing.JTextField textStreet;
    // End of variables declaration                   
}
